### ISSUE TITLE
Duplicated message in comand execution

### ISSUE THREAD

**Issue by MatiusRock1** [cel-ai/celai#54]
![image](https://github.com/user-attachments/assets/e0a861ed-1f04-4a13-b0fa-938ba8a919b0)

![image](https://github.com/user-attachments/assets/4be91fa6-52ca-470b-acfa-be45e0a7e0e6)

**Comment by alejamp** [comment]
There was an issue with history that duplicated user input messages and lost the last tool_message in nested function call.
fixed! 
#57
